<?php require 'templates/layout/header.phtml' ?>

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar</title>
</head>

<body>
    <form method="POST" action="<?= BASE_URL ?>actualizarCliente" class="p-4 border rounded shadow mt-5">

        <input type="hidden" name="cliente_id" value="<?= $cliente->cliente_id ?>">

        <div class="mb-3">
            <label for="cantidad" class="form-label">Nombre</label>
            <input type="text" id="nombre" name="nombre" value="<?= $cliente->nombre ?>" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="apellido" class="form-label">Apellido</label>
            <input type="text" id="apellido" name="apellido" value="<?= $cliente->apellido ?>" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="dni" class="form-label">Dni</label>
            <input type="text" id="dni" name="dni" value="<?= $cliente->dni ?>" class="form-control" required>
        </div>

        <div class="mb-3">
            <label for="obra_social" class="form-label">Obra Social</label>
            <input type="text" id="obra_social" name="obra_social" value="<?= $cliente->obra_social ?>" class="form-control" required>
        </div>

        <button type="submit" class="btn btn-primary">Confirmar</button>
        <a href="<?= BASE_URL ?>clientes" class="btn btn-danger ">Cancelar</a>
    </form>
</body>

</html>

<?php require 'templates/layout/footer.phtml' ?>