<?php require 'templates/layout/header.phtml' ?>

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Farmacia</title>
</head>

<body>

<form method="POST" action="<?= BASE_URL ?>agregarCliente" class="p-4 border rounded shadow">
    <div class="mb-3">
        <label for="nombre" class="form-label">Nombre</label>
        <input type="text" id="nombre" name="nombre" class="form-control" required>
    </div>

    <div class="mb-3">
        <label for="apellido" class="form-label">Apellido</label>
        <input type="text" id="apellido" name="apellido" class="form-control" required>
    </div>

    <div class="mb-3">
        <label for="" class="form-label">DNI</label>
        <input type="number" id="dni" name="dni" class="form-control" required>
    </div>

    <div class="mb-3">
        <label for="obra_social" class="form-label">Obra Social</label>
        <input type="text" id="obra_social" name="obra_social" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary">Crear Cliente</button>
    <a href="<?= BASE_URL ?>clientes" class="btn btn-danger ">Cancelar</a>
</form>

</body>

</html>

<?php require 'templates/layout/footer.phtml' ?>