<?php require 'templates/layout/header.phtml' ?>

<ul class="list-group">
  <?php foreach ($compras as $compra) { ?>
    <li class="list-group-item">
      <div class="d-flex justify-content-between align-items-center">
        
        <div>
          <?php echo $compra->cantidad ?> - <?php echo $compra->fecha_compra ?> - <?php echo $compra->nombre_producto ?> -
          <?php echo $compra->nombre_droga ?> - <?php echo $compra->precio ?> - <?php echo $compra->compra_id ?>
        </div>
        
        <div>
          <a href="visualizar/<?php echo $compra->compra_id; ?>" type="button" class="btn btn-success me-2">Visualizar</a>
          <?php if (isset($_SESSION['USERNAME'])) { ?>
            <a href="verFormActualizar/<?php echo $compra->compra_id; ?>" type="button" class="btn btn-warning me-2">Editar</a>
            <a href="eliminar/<?php echo $compra->compra_id; ?>" type="button" class="btn btn-danger">Eliminar</a>
          <?php } ?>
        </div>
      </div>
    </li>
  <?php } ?>
</ul>

<?php if (isset($_SESSION['USERNAME'])) { ?>
  <p class="mt-3 ms-3"><small>Mostrando <?= $count ?> medicamentos</small></p>
  <a href="verFormAgregar/" type="button" class="btn btn-info ms-3">Agregar medicamento</a>
  <a href="<?= BASE_URL ?>clientes" class="btn btn-info">Ver Clientes</a>
<?php } ?>


<?php require 'templates/layout/footer.phtml' ?>

<?php

// compras hace referencia a los detalles del medicamento