<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Planta</title>
</head>

<body>
    <form method="POST" action="<?= BASE_URL ?>actualizarMedicamento">

        <input type="hidden" name="compra_id" value="<?= $compra->compra_id ?>">

        <label for="monto">Monto</label>
        <input type="text" id="monto" name="monto" value="<?= $compra->monto ?>" required>

        <label for="fecha_compra">Fecha</label>
        <input type="text" id="fecha_compra" name="fecha_compra" value="<?= $compra->fecha_compra ?>" required>

        <label for="nombre_producto">Nombre del producto</label>
        <input type="text" id="nombre_producto" name="nombre_producto" value="<?= $compra->nombre_producto ?>" required>

        <label for="nombre_droga">Nombre de la droga</label>
        <input type="text" id="nombre_droga" name="nombre_droga" value="<?= $compra->nombre_droga ?>" required>

        <label for="precio">Precio</label>
        <input type="number" id="precio" name="precio" value="<?= $compra->precio ?>" required>


        <label for="cliente_id">Seleccione un cliente</label>
        <select id="cliente_id" name="cliente_id">
            <?php foreach ($clientes as $cliente): ?>
                <option value="<?php echo $cliente->cliente_id; ?>"><?= $cliente->nombre; ?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit">Editar medicamento</button>
    </form>
</body>

</html>