<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Farmacia</title>
</head>

<body>

    <form method="POST" action="<?= BASE_URL ?>agregarMedicamento">
        <label for="monto">Monto</label>
        <input type="text" id="monto" name="monto" required>

        <label for="fecha">Fecha</label>
        <input type="text" id="fecha_compra" name="fecha_compra" required>

        <label for="nombre_producto">Nombre del producto</label>
        <input type="text" id="nombre_producto" name="nombre_producto" required>

        <label for="nombre_droga">Nombre de la droga</label>
        <input type="text" id="nombre_droga" name="nombre_droga" required>

        <label for="precio">Precio</label>
        <input type="number" id="precio" name="precio" required>

        <label for="cliente_id">Seleccione un cliente</label>
        <select id="cliente_id" name="cliente_id" required>
            <?php foreach ($clientes as $cliente): ?>
                <option value="<?php echo $cliente->cliente_id; ?>"><?= $cliente->nombre; ?></option>
            <?php endforeach; ?>
        </select>
        <button type="submit">Agregar medicamento</button>
    </form>

</body>

</html>