<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/style.css">
    <title>Titulo</title>
</head>

<body>
    <header>
    <nav class="navbar navbar-expand-lg navbar-custom">
            <div class="container-fluid">
                <a class="navbar-brand" href="inicio">Farmacia - Inicio</a>
                <div class="d-flex align-items-center">
                    <?php if (isset($_SESSION['USERNAME'])): ?>
                        <span class="navbar-text me-3"><?= htmlspecialchars($_SESSION['USERNAME']); ?></span>
                        <!-- Botón de Cerrar sesión -->
                        <form method="post" action="authController.php?action=logout" class="d-inline">
                            <button type="submit" class="btn btn-outline-dark">Cerrar sesión</button>
                        </form>
                    <?php else: ?>
                        <!-- Botón de Login -->
                        <a href="login" class="btn btn-outline-dark">Login</a>
                    <?php endif; ?>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>